<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <PackageId>Feather.Grpc</PackageId>
    <Version>1.1.0</Version>
    <Authors>FeatherTools</Authors>
    <Description>Library with low and high level helpers for gRPC.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/FeatherTools/grpc</PackageProjectUrl>
    <RepositoryUrl>https://github.com/FeatherTools/grpc.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>fsharp;grpc;encoding;serialization</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="src/Utils.fs" />
    <Compile Include="src/Grpc.fs" />
    <Compile Include="src/Error.fs" />
    <Compile Include="src/CoreTypes.fs" />
    <Compile Include="src/Auth.fs" />
    <Compile Include="src/Metrics.fs" />
    <Compile Include="src/Serialization.fs" />
    <Compile Include="src/HighLevel.fs" />
  </ItemGroup>

  <Import Project=".paket\Paket.Restore.targets" />

</Project>
